# -*- coding: utf-8 -*-
"""ALIMI_ABANISELOLUWA_BU22CSC1114.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VzHmBFRVaA_IxulLUEW_N1Q-lL6mO6AO
"""

# ============================================================
# EMPLOYEE PERFORMANCE PREDICTION SYSTEM
# Comparison of TabTransformer vs GAN-Transformer with SHAP
# Author: Abaniseloluwa Micheal Alimi | BU22CSC1114
# Bowen University | June 2026
# ============================================================

# ============================================================
# STEP 1: INSTALL LIBRARIES
# ============================================================
!pip install pytorch-tabular ctgan shap imbalanced-learn xlrd -q
print("Libraries installed successfully.")

# ============================================================
# STEP 2: IMPORT LIBRARIES
# ============================================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import torch
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
    f1_score, roc_auc_score, matthews_corrcoef,
    confusion_matrix, classification_report, roc_curve, auc)
from imblearn.over_sampling import SMOTE
from ctgan import CTGAN
from pytorch_tabular import TabularModel
from pytorch_tabular.models import TabTransformerConfig
from pytorch_tabular.config import DataConfig, OptimizerConfig, TrainerConfig

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
print("Libraries imported successfully.")
print(f"GPU available: {torch.cuda.is_available()}")

# ============================================================
# STEP 3: UPLOAD AND LOAD DATASET
# ============================================================
from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]
df = pd.read_excel(filename, engine='xlrd')

print(f"Dataset loaded: {filename}")
print(f"Shape: {df.shape}")
print(f"\nPerformanceRating distribution:")
print(df['PerformanceRating'].value_counts().sort_index())

# ============================================================
# STEP 4: BINARY TARGET ENGINEERING AND SMOTE BALANCING
# ============================================================
# Binary target: Rating 4 = High Performance (1), else Low (0)
df['PerformanceBinary'] = df['PerformanceRating'].apply(
    lambda x: 1 if x == 4 else 0)
TARGET = 'PerformanceBinary'

print("Binary distribution BEFORE SMOTE:")
print(df[TARGET].value_counts())

# Drop unnecessary columns
cols_to_drop = [c for c in ['PerformanceRating', 'Attrition', 'EmpNumber']
                if c in df.columns]
X = df.drop(columns=cols_to_drop + [TARGET])
y = df[TARGET].copy()

# Identify feature types
CAT_COLS = X.select_dtypes(include=['object', 'category']).columns.tolist()
NUM_COLS = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
for col in CAT_COLS:
    X[col] = X[col].astype(str)

print(f"\nCategorical features ({len(CAT_COLS)}): {CAT_COLS}")
print(f"Numerical features  ({len(NUM_COLS)}): {NUM_COLS}")

# Encode for SMOTE
X_encoded = X.copy()
le_dict = {}
for col in CAT_COLS:
    le = LabelEncoder()
    X_encoded[col] = le.fit_transform(X[col])
    le_dict[col] = le

# Apply SMOTE
smote = SMOTE(random_state=SEED, sampling_strategy=1.0)
X_res, y_res = smote.fit_resample(X_encoded, y)

# Decode back to original categorical values
for col in CAT_COLS:
    X_res[col] = le_dict[col].inverse_transform(
        X_res[col].astype(int)).astype(str)

X = X_res.reset_index(drop=True)
y = pd.Series(y_res).reset_index(drop=True)

print(f"\nClass distribution AFTER SMOTE:")
print(y.value_counts())
print(f"Total samples: {len(X)}")

# ============================================================
# STEP 5: TRAIN/TEST SPLIT
# ============================================================
X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, y, test_size=0.15, random_state=SEED, stratify=y)

print(f"Train+Val : {len(X_trainval)} samples")
print(f"Test set  : {len(X_test)} samples")
print(f"\nTest class balance:")
print(y_test.value_counts())
print("Data preparation complete.")

# ============================================================
# STEP 6: MODEL 1 — TABTRANSFORMER 5-FOLD CROSS VALIDATION
# ============================================================
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
tab_metrics = {'accuracy':[], 'precision':[], 'recall':[],
               'f1':[], 'auc':[], 'mcc':[]}

print('='*60)
print('MODEL 1: TabTransformer - 5-Fold Cross Validation')
print('='*60)

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trainval, y_trainval)):
    print(f'\nFold {fold+1}/5...')
    X_tr = X_trainval.iloc[train_idx].reset_index(drop=True)
    y_tr = y_trainval.iloc[train_idx].reset_index(drop=True)
    X_val = X_trainval.iloc[val_idx].reset_index(drop=True)
    y_val = y_trainval.iloc[val_idx].reset_index(drop=True)

    train_df = X_tr.copy(); train_df[TARGET] = y_tr.values
    val_df = X_val.copy(); val_df[TARGET] = y_val.values

    data_config = DataConfig(
        target=[TARGET],
        continuous_cols=NUM_COLS,
        categorical_cols=CAT_COLS)

    trainer_config = TrainerConfig(
        auto_lr_find=False,
        batch_size=32,
        max_epochs=200,
        early_stopping='valid_loss',
        early_stopping_patience=20,
        checkpoints='valid_loss',
        load_best=True,
        progress_bar='none',
        trainer_kwargs={'enable_model_summary': False})

    optimizer_config = OptimizerConfig(
        optimizer='AdamW',
        optimizer_params={'weight_decay': 1e-4},
        lr_scheduler='CosineAnnealingWarmRestarts',
        lr_scheduler_params={'T_0': 50, 'T_mult': 2})

    model_config = TabTransformerConfig(
        task='classification',
        input_embed_dim=64,
        num_heads=8,
        num_attn_blocks=8,
        ff_hidden_multiplier=4,
        attn_dropout=0.1,
        ff_dropout=0.1,
        learning_rate=3e-4,
        metrics=['accuracy'])

    model = TabularModel(
        data_config=data_config,
        model_config=model_config,
        optimizer_config=optimizer_config,
        trainer_config=trainer_config,
        verbose=False)

    model.fit(train=train_df, validation=val_df)

    preds = model.predict(X_val)
    pred_col = [c for c in preds.columns if 'prediction' in c.lower()][0]
    y_pred = preds[pred_col].values.astype(int)
    prob_cols = [c for c in preds.columns if '1' in c and 'probability' in c.lower()]
    y_prob = preds[prob_cols[0]].values if prob_cols else y_pred

    tab_metrics['accuracy'].append(accuracy_score(y_val, y_pred))
    tab_metrics['precision'].append(precision_score(y_val, y_pred, zero_division=0))
    tab_metrics['recall'].append(recall_score(y_val, y_pred, zero_division=0))
    tab_metrics['f1'].append(f1_score(y_val, y_pred, zero_division=0))
    tab_metrics['auc'].append(roc_auc_score(y_val, y_prob))
    tab_metrics['mcc'].append(matthews_corrcoef(y_val, y_pred))

    print(f'  Accuracy: {tab_metrics["accuracy"][-1]:.4f} | '
          f'AUC: {tab_metrics["auc"][-1]:.4f}')

    if fold == 4:
        tab_model_final = model
        X_val_final = X_val.copy()

print('\n' + '='*60)
print('TABTRANSFORMER CROSS-VALIDATION RESULTS')
print('='*60)
for m, v in tab_metrics.items():
    print(f'{m:12s}: {np.mean(v):.4f} +/- {np.std(v):.4f}')

# ============================================================
# STEP 7: TABTRANSFORMER FINAL TEST SET EVALUATION
# ============================================================
test_preds = tab_model_final.predict(X_test)
pred_col = [c for c in test_preds.columns if 'prediction' in c.lower()][0]
y_test_pred_tab = test_preds[pred_col].values.astype(int)
prob_cols = [c for c in test_preds.columns if '1' in c and 'probability' in c.lower()]
y_test_prob_tab = test_preds[prob_cols[0]].values if prob_cols else y_test_pred_tab

print('='*60)
print('TABTRANSFORMER - FINAL TEST SET RESULTS')
print('='*60)
print(f'Accuracy : {accuracy_score(y_test, y_test_pred_tab):.4f}')
print(f'Precision: {precision_score(y_test, y_test_pred_tab, zero_division=0):.4f}')
print(f'Recall   : {recall_score(y_test, y_test_pred_tab, zero_division=0):.4f}')
print(f'F1-Score : {f1_score(y_test, y_test_pred_tab, zero_division=0):.4f}')
print(f'ROC-AUC  : {roc_auc_score(y_test, y_test_prob_tab):.4f}')
print(f'MCC      : {matthews_corrcoef(y_test, y_test_pred_tab):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_test_pred_tab,
      target_names=['Low Performance', 'High Performance']))

# Confusion Matrix
cm_tab = confusion_matrix(y_test, y_test_pred_tab)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_tab, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Low', 'High'],
            yticklabels=['Low', 'High'],
            linewidths=1, linecolor='white')
plt.title('TabTransformer Confusion Matrix', fontsize=13, fontweight='bold')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig('figure_3_tabtransformer_confusion_matrix.png', bbox_inches='tight')
plt.show()

# ============================================================
# STEP 8: TABTRANSFORMER SHAP ANALYSIS
# ============================================================
print('Running SHAP analysis for TabTransformer...')

def tab_predict_proba(data_array):
    df_input = pd.DataFrame(data_array, columns=X.columns)
    for col in CAT_COLS:
        df_input[col] = df_input[col].astype(str)
    for col in NUM_COLS:
        if col in df_input.columns:
            df_input[col] = pd.to_numeric(df_input[col], errors='coerce').fillna(0)
    preds = tab_model_final.predict(df_input)
    prob_cols = [c for c in preds.columns if 'probability' in c.lower()]
    if prob_cols:
        return preds[prob_cols].values
    return np.column_stack([1-preds.iloc[:,0].values, preds.iloc[:,0].values])

background = X_val_final.iloc[:50].values.astype(str)
explainer_tab = shap.KernelExplainer(tab_predict_proba, background)
shap_values_tab = explainer_tab.shap_values(
    X_val_final.iloc[:100].values.astype(str), nsamples=100)

sv_tab = np.array(shap_values_tab)[:,:,1]
X_shap = X_val_final.iloc[:100].reset_index(drop=True)

plt.figure(figsize=(10, 7))
shap.summary_plot(sv_tab, X_shap, feature_names=X.columns.tolist(),
    plot_type='bar', show=False, color='steelblue')
plt.title('TabTransformer - SHAP Global Feature Importance',
          fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('figure_4_shap_tabtransformer_global.png', bbox_inches='tight')
plt.show()

plt.figure(figsize=(10, 7))
shap.summary_plot(sv_tab, X_shap, feature_names=X.columns.tolist(), show=False)
plt.title('TabTransformer - SHAP Beeswarm Plot', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('figure_5_shap_tabtransformer_beeswarm.png', bbox_inches='tight')
plt.show()

mean_importance = np.abs(sv_tab).mean(axis=0).flatten()
min_len = min(len(X.columns.tolist()), len(mean_importance))
tab_feature_importance = pd.DataFrame({
    'Feature': X.columns.tolist()[:min_len],
    'SHAP_Importance': mean_importance[:min_len]
}).sort_values('SHAP_Importance', ascending=False)

print('TabTransformer SHAP analysis complete.')
print('\nTop 10 Features (TabTransformer):')
print(tab_feature_importance.head(10).to_string(index=False))

# ============================================================
# STEP 9: CTGAN SYNTHETIC DATA GENERATION
# ============================================================
print('='*60)
print('CTGAN - Synthetic Data Generation')
print('='*60)

train_for_gan = X_trainval.copy()
train_for_gan[TARGET] = y_trainval.values
discrete_cols = CAT_COLS + [TARGET]

ctgan = CTGAN(
    epochs=300,
    batch_size=500,
    generator_dim=(256, 256),
    discriminator_dim=(256, 256),
    pac=10,
    verbose=True)

print('Training CTGAN...')
ctgan.fit(train_for_gan, discrete_columns=discrete_cols)
synthetic_data = ctgan.sample(len(X_trainval))

syn_high = synthetic_data[synthetic_data[TARGET]==1]
syn_low = synthetic_data[synthetic_data[TARGET]==0]
syn_low_up = syn_low.sample(n=len(syn_high), replace=True, random_state=SEED)
synthetic_data = pd.concat([syn_high, syn_low_up],
    ignore_index=True).sample(frac=1, random_state=SEED).reset_index(drop=True)

syn_X = synthetic_data.drop(columns=[TARGET])
syn_y = synthetic_data[TARGET]
for col in CAT_COLS:
    if col in syn_X.columns:
        syn_X[col] = syn_X[col].astype(str)

print(f'Generated {len(synthetic_data)} synthetic records.')
print(f'Class balance: {synthetic_data[TARGET].value_counts().to_dict()}')

# ============================================================
# STEP 10: MODEL 2 — GAN-TRANSFORMER 5-FOLD CROSS VALIDATION
# ============================================================
gan_metrics = {'accuracy':[], 'precision':[], 'recall':[],
               'f1':[], 'auc':[], 'mcc':[]}

print('='*60)
print('MODEL 2: GAN-Transformer - 5-Fold Cross Validation')
print('='*60)

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trainval, y_trainval)):
    print(f'\nFold {fold+1}/5...')
    X_tr = X_trainval.iloc[train_idx].reset_index(drop=True)
    y_tr = y_trainval.iloc[train_idx].reset_index(drop=True)
    X_val = X_trainval.iloc[val_idx].reset_index(drop=True)
    y_val = y_trainval.iloc[val_idx].reset_index(drop=True)

    X_tr_aug = pd.concat([X_tr, syn_X], ignore_index=True)
    y_tr_aug = pd.concat([y_tr, syn_y], ignore_index=True)
    for col in CAT_COLS:
        if col in X_tr_aug.columns:
            X_tr_aug[col] = X_tr_aug[col].astype(str)
    for col in NUM_COLS:
        if col in X_tr_aug.columns:
            X_tr_aug[col] = pd.to_numeric(X_tr_aug[col], errors='coerce').fillna(0)

    train_aug_df = X_tr_aug.copy(); train_aug_df[TARGET] = y_tr_aug.values
    val_df = X_val.copy(); val_df[TARGET] = y_val.values

    data_config = DataConfig(
        target=[TARGET],
        continuous_cols=NUM_COLS,
        categorical_cols=CAT_COLS)

    trainer_config = TrainerConfig(
        auto_lr_find=False,
        batch_size=32,
        max_epochs=200,
        early_stopping='valid_loss',
        early_stopping_patience=20,
        checkpoints='valid_loss',
        load_best=True,
        progress_bar='none',
        trainer_kwargs={'enable_model_summary': False})

    optimizer_config = OptimizerConfig(
        optimizer='AdamW',
        optimizer_params={'weight_decay': 1e-4},
        lr_scheduler='CosineAnnealingWarmRestarts',
        lr_scheduler_params={'T_0': 50, 'T_mult': 2})

    model_config = TabTransformerConfig(
        task='classification',
        input_embed_dim=64,
        num_heads=8,
        num_attn_blocks=8,
        ff_hidden_multiplier=4,
        attn_dropout=0.1,
        ff_dropout=0.1,
        learning_rate=3e-4,
        metrics=['accuracy'])

    gan_model = TabularModel(
        data_config=data_config,
        model_config=model_config,
        optimizer_config=optimizer_config,
        trainer_config=trainer_config,
        verbose=False)

    gan_model.fit(train=train_aug_df, validation=val_df)

    preds = gan_model.predict(X_val)
    pred_col = [c for c in preds.columns if 'prediction' in c.lower()][0]
    y_pred = preds[pred_col].values.astype(int)
    prob_cols = [c for c in preds.columns if '1' in c and 'probability' in c.lower()]
    y_prob = preds[prob_cols[0]].values if prob_cols else y_pred

    gan_metrics['accuracy'].append(accuracy_score(y_val, y_pred))
    gan_metrics['precision'].append(precision_score(y_val, y_pred, zero_division=0))
    gan_metrics['recall'].append(recall_score(y_val, y_pred, zero_division=0))
    gan_metrics['f1'].append(f1_score(y_val, y_pred, zero_division=0))
    gan_metrics['auc'].append(roc_auc_score(y_val, y_prob))
    gan_metrics['mcc'].append(matthews_corrcoef(y_val, y_pred))

    print(f'  Accuracy: {gan_metrics["accuracy"][-1]:.4f} | '
          f'AUC: {gan_metrics["auc"][-1]:.4f}')

    if fold == 4:
        gan_model_final = gan_model
        X_val_gan_final = X_val.copy()

print('\n' + '='*60)
print('GAN-TRANSFORMER CROSS-VALIDATION RESULTS')
print('='*60)
for m, v in gan_metrics.items():
    print(f'{m:12s}: {np.mean(v):.4f} +/- {np.std(v):.4f}')

# ============================================================
# STEP 11: GAN-TRANSFORMER FINAL TEST SET EVALUATION
# ============================================================
test_preds_gan = gan_model_final.predict(X_test)
pred_col = [c for c in test_preds_gan.columns if 'prediction' in c.lower()][0]
y_test_pred_gan = test_preds_gan[pred_col].values.astype(int)
prob_cols = [c for c in test_preds_gan.columns if '1' in c and 'probability' in c.lower()]
y_test_prob_gan = test_preds_gan[prob_cols[0]].values if prob_cols else y_test_pred_gan

print('='*60)
print('GAN-TRANSFORMER - FINAL TEST SET RESULTS')
print('='*60)
print(f'Accuracy : {accuracy_score(y_test, y_test_pred_gan):.4f}')
print(f'Precision: {precision_score(y_test, y_test_pred_gan, zero_division=0):.4f}')
print(f'Recall   : {recall_score(y_test, y_test_pred_gan, zero_division=0):.4f}')
print(f'F1-Score : {f1_score(y_test, y_test_pred_gan, zero_division=0):.4f}')
print(f'ROC-AUC  : {roc_auc_score(y_test, y_test_prob_gan):.4f}')
print(f'MCC      : {matthews_corrcoef(y_test, y_test_pred_gan):.4f}')
print('\nClassification Report:')
print(classification_report(y_test, y_test_pred_gan,
      target_names=['Low Performance', 'High Performance']))

# Confusion Matrix
cm_gan = confusion_matrix(y_test, y_test_pred_gan)
plt.figure(figsize=(6, 5))
sns.heatmap(cm_gan, annot=True, fmt='d', cmap='Greens',
            xticklabels=['Low', 'High'],
            yticklabels=['Low', 'High'],
            linewidths=1, linecolor='white')
plt.title('GAN-Transformer Confusion Matrix', fontsize=13, fontweight='bold')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.tight_layout()
plt.savefig('figure_6_gan_transformer_confusion_matrix.png', bbox_inches='tight')
plt.show()

# ============================================================
# STEP 12: GAN-TRANSFORMER SHAP ANALYSIS
# ============================================================
print('Running SHAP analysis for GAN-Transformer...')

def gan_predict_proba(data_array):
    df_input = pd.DataFrame(data_array, columns=X.columns)
    for col in CAT_COLS:
        df_input[col] = df_input[col].astype(str)
    for col in NUM_COLS:
        if col in df_input.columns:
            df_input[col] = pd.to_numeric(df_input[col], errors='coerce').fillna(0)
    preds = gan_model_final.predict(df_input)
    prob_cols = [c for c in preds.columns if 'probability' in c.lower()]
    if prob_cols:
        return preds[prob_cols].values
    return np.column_stack([1-preds.iloc[:,0].values, preds.iloc[:,0].values])

background_gan = X_val_gan_final.iloc[:50].values.astype(str)
explainer_gan = shap.KernelExplainer(gan_predict_proba, background_gan)
shap_values_gan = explainer_gan.shap_values(
    X_val_gan_final.iloc[:100].values.astype(str), nsamples=100)

sv_gan = np.array(shap_values_gan)[:,:,1]
X_shap_gan = X_val_gan_final.iloc[:100].reset_index(drop=True)

plt.figure(figsize=(10, 7))
shap.summary_plot(sv_gan, X_shap_gan, feature_names=X.columns.tolist(),
    plot_type='bar', show=False, color='#2ecc71')
plt.title('GAN-Transformer - SHAP Global Feature Importance',
          fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('figure_7_shap_gan_global.png', bbox_inches='tight')
plt.show()

plt.figure(figsize=(10, 7))
shap.summary_plot(sv_gan, X_shap_gan, feature_names=X.columns.tolist(), show=False)
plt.title('GAN-Transformer - SHAP Beeswarm Plot', fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('figure_8_shap_gan_beeswarm.png', bbox_inches='tight')
plt.show()

mean_importance_gan = np.abs(sv_gan).mean(axis=0).flatten()
min_len = min(len(X.columns.tolist()), len(mean_importance_gan))
gan_feature_importance = pd.DataFrame({
    'Feature': X.columns.tolist()[:min_len],
    'SHAP_Importance': mean_importance_gan[:min_len]
}).sort_values('SHAP_Importance', ascending=False)

print('GAN-Transformer SHAP analysis complete.')
print('\nTop 10 Features (GAN-Transformer):')
print(gan_feature_importance.head(10).to_string(index=False))

# ============================================================
# STEP 13: COMPARATIVE RESULTS
# ============================================================
print('='*70)
print('FINAL COMPARATIVE RESULTS')
print('='*70)

metrics_names = ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC', 'MCC']
tab_vals = [
    accuracy_score(y_test, y_test_pred_tab),
    precision_score(y_test, y_test_pred_tab, zero_division=0),
    recall_score(y_test, y_test_pred_tab, zero_division=0),
    f1_score(y_test, y_test_pred_tab, zero_division=0),
    roc_auc_score(y_test, y_test_prob_tab),
    matthews_corrcoef(y_test, y_test_pred_tab)
]
gan_vals = [
    accuracy_score(y_test, y_test_pred_gan),
    precision_score(y_test, y_test_pred_gan, zero_division=0),
    recall_score(y_test, y_test_pred_gan, zero_division=0),
    f1_score(y_test, y_test_pred_gan, zero_division=0),
    roc_auc_score(y_test, y_test_prob_gan),
    matthews_corrcoef(y_test, y_test_pred_gan)
]

print(f'{"Metric":<15} {"TabTransformer":>15} {"GAN-Transformer":>15} {"Winner":>15}')
print('-'*65)
for i, m in enumerate(metrics_names):
    winner = 'TabTransformer' if tab_vals[i] > gan_vals[i] else 'GAN-Transformer'
    print(f'{m:<15} {tab_vals[i]:>15.4f} {gan_vals[i]:>15.4f} {winner:>15}')

# Comparison Bar Chart
x = np.arange(len(metrics_names))
width = 0.35
fig, ax = plt.subplots(figsize=(12, 6))
bars1 = ax.bar(x - width/2, tab_vals, width, label='TabTransformer',
               color='steelblue', alpha=0.85, edgecolor='white')
bars2 = ax.bar(x + width/2, gan_vals, width, label='GAN-Transformer',
               color='#2ecc71', alpha=0.85, edgecolor='white')
ax.set_ylabel('Score', fontsize=12)
ax.set_title('TabTransformer vs GAN-Transformer - All Metrics Comparison',
             fontsize=13, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(metrics_names, fontsize=11)
ax.legend(fontsize=11)
ax.set_ylim(0, 1.15)
ax.axhline(y=0.90, color='red', linestyle='--', alpha=0.5)
for bar in bars1:
    ax.annotate(f'{bar.get_height():.3f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 4), textcoords='offset points',
                ha='center', fontsize=9, color='steelblue', fontweight='bold')
for bar in bars2:
    ax.annotate(f'{bar.get_height():.3f}',
                xy=(bar.get_x() + bar.get_width()/2, bar.get_height()),
                xytext=(0, 4), textcoords='offset points',
                ha='center', fontsize=9, color='#27ae60', fontweight='bold')
plt.tight_layout()
plt.savefig('figure_9_comparative_metrics.png', bbox_inches='tight')
plt.show()

# SHAP Side-by-Side Comparison
top_n = 10
top_tab = tab_feature_importance.head(top_n)
top_gan = gan_feature_importance.head(top_n)
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
axes[0].barh(top_tab['Feature'][::-1], top_tab['SHAP_Importance'][::-1],
             color='steelblue', alpha=0.85)
axes[0].set_title('TabTransformer\nSHAP Feature Importance',
                  fontsize=12, fontweight='bold')
axes[0].set_xlabel('Mean |SHAP Value|')
axes[1].barh(top_gan['Feature'][::-1], top_gan['SHAP_Importance'][::-1],
             color='#2ecc71', alpha=0.85)
axes[1].set_title('GAN-Transformer\nSHAP Feature Importance',
                  fontsize=12, fontweight='bold')
axes[1].set_xlabel('Mean |SHAP Value|')
fig.suptitle('SHAP Feature Importance Comparison - TabTransformer vs GAN-Transformer',
             fontsize=13, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('figure_10_shap_comparison.png', bbox_inches='tight')
plt.show()

# ============================================================
# STEP 14: ROC CURVE
# ============================================================
fpr_tab, tpr_tab, _ = roc_curve(y_test, y_test_prob_tab)
fpr_gan, tpr_gan, _ = roc_curve(y_test, y_test_prob_gan)
auc_tab = auc(fpr_tab, tpr_tab)
auc_gan = auc(fpr_gan, tpr_gan)

plt.figure(figsize=(8, 6))
plt.plot(fpr_tab, tpr_tab, color='steelblue', lw=2,
         label=f'TabTransformer (AUC = {auc_tab:.4f})')
plt.plot(fpr_gan, tpr_gan, color='#2ecc71', lw=2,
         label=f'GAN-Transformer (AUC = {auc_gan:.4f})')
plt.plot([0, 1], [0, 1], color='gray', linestyle='--', lw=1,
         label='Random Classifier (AUC = 0.50)')
plt.xlabel('False Positive Rate', fontsize=12)
plt.ylabel('True Positive Rate', fontsize=12)
plt.title('ROC Curve - TabTransformer vs GAN-Transformer',
          fontsize=13, fontweight='bold')
plt.legend(loc='lower right', fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('figure_11_roc_curve.png', bbox_inches='tight')
plt.show()

# ============================================================
# STEP 15: SAVE ALL RESULTS
# ============================================================
summary = pd.DataFrame({
    'Model': ['TabTransformer', 'GAN-Transformer'],
    'Accuracy': [tab_vals[0], gan_vals[0]],
    'Precision': [tab_vals[1], gan_vals[1]],
    'Recall': [tab_vals[2], gan_vals[2]],
    'F1_Score': [tab_vals[3], gan_vals[3]],
    'ROC_AUC': [tab_vals[4], gan_vals[4]],
    'MCC': [tab_vals[5], gan_vals[5]]
})
summary.to_csv('results_summary.csv', index=False)
tab_feature_importance.to_csv('shap_tabtransformer.csv', index=False)
gan_feature_importance.to_csv('shap_gan_transformer.csv', index=False)

print('All results saved successfully.')
print('Files saved:')
print('  - results_summary.csv')
print('  - shap_tabtransformer.csv')
print('  - shap_gan_transformer.csv')
print('  - figure_3 to figure_11 (PNG images)')
print('Implementation complete.')