# -*- coding: utf-8 -*-
"""TabTransformer (SMOTE) vs GAN-Transformer (CTGAN).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvgWxS4ZyvvvJDLtWrcpkjl4gSHLdinD
"""

# ============================================================
# COMPLETE CODE - NEW NOTEBOOK
# TabTransformer (SMOTE) vs GAN-Transformer (CTGAN)
# ============================================================

# ---------- 1. Install Libraries ----------
!pip install pytorch-tabular ctgan shap imbalanced-learn xlrd -q

# ---------- 2. Import Libraries ----------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import warnings
warnings.filterwarnings('ignore')

from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score,
                             roc_auc_score, matthews_corrcoef, confusion_matrix,
                             classification_report, roc_curve, auc)
from imblearn.over_sampling import SMOTE
from ctgan import CTGAN
from pytorch_tabular import TabularModel
from pytorch_tabular.models import TabTransformerConfig
from pytorch_tabular.config import DataConfig, OptimizerConfig, TrainerConfig

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
sns.set(style="whitegrid")

# ---------- 3. Upload & Load Dataset ----------
from google.colab import files
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Automatically detect file type
if filename.endswith('.csv'):
    df = pd.read_csv(filename)
else:
    df = pd.read_excel(filename, engine='xlrd')

print(f"Dataset loaded: {filename}")
print(f"Shape: {df.shape}")

# ---------- 4. Prepare Data (INX Dataset style) ----------
# Binary target
df['PerformanceBinary'] = df['PerformanceRating'].apply(lambda x: 1 if x == 4 else 0)
TARGET = 'PerformanceBinary'

cols_to_drop = [c for c in ['PerformanceRating', 'Attrition', 'EmpNumber'] if c in df.columns]
X = df.drop(columns=cols_to_drop + [TARGET])
y = df[TARGET].copy()

CAT_COLS = X.select_dtypes(include=['object', 'category']).columns.tolist()
NUM_COLS = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

for col in CAT_COLS:
    X[col] = X[col].astype(str)

print("Binary class distribution:")
print(y.value_counts())

# Train/Test Split
X_trainval, X_test, y_trainval, y_test = train_test_split(
    X, y, test_size=0.15, random_state=SEED, stratify=y)

print(f"Train+Val: {len(X_trainval)} | Test: {len(X_test)}")

# ---------- Helper: Best Threshold ----------
def find_best_threshold(y_true, y_probs):
    best_thresh = 0.5
    best_f1 = 0
    for thresh in np.arange(0.25, 0.75, 0.01):
        preds = (y_probs >= thresh).astype(int)
        current_f1 = f1_score(y_true, preds, zero_division=0)
        if current_f1 > best_f1:
            best_f1 = current_f1
            best_thresh = thresh
    return best_thresh

# ============================================================
# MODEL 1: TabTransformer (SMOTE)
# ============================================================
print("\n" + "="*60)
print("MODEL 1: TabTransformer (SMOTE)")
print("="*60)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=SEED)
tab_metrics = {'accuracy':[], 'precision':[], 'recall':[], 'f1':[], 'auc':[], 'mcc':[]}

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trainval, y_trainval)):
    print(f"\nFold {fold+1}/5...")

    X_tr = X_trainval.iloc[train_idx].reset_index(drop=True)
    y_tr = y_trainval.iloc[train_idx].reset_index(drop=True)
    X_val = X_trainval.iloc[val_idx].reset_index(drop=True)
    y_val = y_trainval.iloc[val_idx].reset_index(drop=True)

    # SMOTE
    X_tr_enc = X_tr.copy()
    le_dict = {}
    for col in CAT_COLS:
        le = LabelEncoder()
        X_tr_enc[col] = le.fit_transform(X_tr[col].astype(str))
        le_dict[col] = le

    smote = SMOTE(random_state=SEED, sampling_strategy=0.75)
    X_res, y_res = smote.fit_resample(X_tr_enc, y_tr)

    X_tr_aug = X_res.copy()
    for col in CAT_COLS:
        X_tr_aug[col] = le_dict[col].inverse_transform(X_tr_aug[col].astype(int)).astype(str)
    for col in NUM_COLS:
        X_tr_aug[col] = pd.to_numeric(X_tr_aug[col], errors='coerce').fillna(0)

    train_df = X_tr_aug.copy()
    train_df[TARGET] = y_res
    val_df = X_val.copy()
    val_df[TARGET] = y_val.values

    data_config = DataConfig(target=[TARGET], continuous_cols=NUM_COLS, categorical_cols=CAT_COLS)
    trainer_config = TrainerConfig(
        auto_lr_find=False, batch_size=32, max_epochs=150,
        early_stopping='valid_loss', early_stopping_patience=15,
        checkpoints='valid_loss', load_best=True, progress_bar='none',
        trainer_kwargs={'enable_model_summary': False}
    )
    optimizer_config = OptimizerConfig(optimizer='AdamW', optimizer_params={'weight_decay': 1e-4})
    model_config = TabTransformerConfig(
        task='classification', input_embed_dim=64, num_heads=8,
        num_attn_blocks=6, learning_rate=3e-4, metrics=['accuracy']
    )

    model = TabularModel(
        data_config=data_config, model_config=model_config,
        optimizer_config=optimizer_config, trainer_config=trainer_config, verbose=False
    )
    model.fit(train=train_df, validation=val_df)

    preds = model.predict(X_val)
    pred_col = [c for c in preds.columns if 'prediction' in c.lower()][0]
    y_pred = preds[pred_col].values.astype(int)
    prob_cols = [c for c in preds.columns if '1' in c and 'probability' in c.lower()]
    y_prob = preds[prob_cols[0]].values if prob_cols else y_pred

    best_thresh = find_best_threshold(y_val, y_prob)
    y_pred_tuned = (y_prob >= best_thresh).astype(int)

    tab_metrics['accuracy'].append(accuracy_score(y_val, y_pred_tuned))
    tab_metrics['precision'].append(precision_score(y_val, y_pred_tuned, zero_division=0))
    tab_metrics['recall'].append(recall_score(y_val, y_pred_tuned, zero_division=0))
    tab_metrics['f1'].append(f1_score(y_val, y_pred_tuned, zero_division=0))
    tab_metrics['auc'].append(roc_auc_score(y_val, y_prob))
    tab_metrics['mcc'].append(matthews_corrcoef(y_val, y_pred_tuned))

    print(f"  Acc: {tab_metrics['accuracy'][-1]:.4f} | F1: {tab_metrics['f1'][-1]:.4f} | AUC: {tab_metrics['auc'][-1]:.4f}")

    if fold == 4:
        tab_model_final = model

print("\nTabTransformer CV Results:")
for m, v in tab_metrics.items():
    print(f"{m:12s}: {np.mean(v):.4f} ± {np.std(v):.4f}")

# ============================================================
# MODEL 2: GAN-Transformer (CTGAN)
# ============================================================
print("\n" + "="*60)
print("MODEL 2: GAN-Transformer (CTGAN)")
print("="*60)

gan_metrics = {'accuracy':[], 'precision':[], 'recall':[], 'f1':[], 'auc':[], 'mcc':[]}

for fold, (train_idx, val_idx) in enumerate(skf.split(X_trainval, y_trainval)):
    print(f"\nFold {fold+1}/5...")

    X_tr = X_trainval.iloc[train_idx].reset_index(drop=True)
    y_tr = y_trainval.iloc[train_idx].reset_index(drop=True)
    X_val = X_trainval.iloc[val_idx].reset_index(drop=True)
    y_val = y_trainval.iloc[val_idx].reset_index(drop=True)

    # CTGAN
    train_fold = X_tr.copy()
    train_fold[TARGET] = y_tr.values
    discrete_cols = CAT_COLS + [TARGET]

    ctgan = CTGAN(epochs=150, batch_size=500, generator_dim=(256, 256),
                  discriminator_dim=(256, 256), pac=10, verbose=False)
    ctgan.fit(train_fold, discrete_columns=discrete_cols)

    synthetic = ctgan.sample(len(X_tr))
    syn_X = synthetic.drop(columns=[TARGET])
    syn_y = synthetic[TARGET]
    for col in CAT_COLS:
        syn_X[col] = syn_X[col].astype(str)

    X_tr_aug = pd.concat([X_tr, syn_X], ignore_index=True)
    y_tr_aug = pd.concat([y_tr, syn_y], ignore_index=True)

    for col in CAT_COLS:
        X_tr_aug[col] = X_tr_aug[col].astype(str)
    for col in NUM_COLS:
        X_tr_aug[col] = pd.to_numeric(X_tr_aug[col], errors='coerce').fillna(0)

    train_df = X_tr_aug.copy()
    train_df[TARGET] = y_tr_aug.values
    val_df = X_val.copy()
    val_df[TARGET] = y_val.values

    model = TabularModel(
        data_config=data_config, model_config=model_config,
        optimizer_config=optimizer_config, trainer_config=trainer_config, verbose=False
    )
    model.fit(train=train_df, validation=val_df)

    preds = model.predict(X_val)
    pred_col = [c for c in preds.columns if 'prediction' in c.lower()][0]
    y_pred = preds[pred_col].values.astype(int)
    prob_cols = [c for c in preds.columns if '1' in c and 'probability' in c.lower()]
    y_prob = preds[prob_cols[0]].values if prob_cols else y_pred

    best_thresh = find_best_threshold(y_val, y_prob)
    y_pred_tuned = (y_prob >= best_thresh).astype(int)

    gan_metrics['accuracy'].append(accuracy_score(y_val, y_pred_tuned))
    gan_metrics['precision'].append(precision_score(y_val, y_pred_tuned, zero_division=0))
    gan_metrics['recall'].append(recall_score(y_val, y_pred_tuned, zero_division=0))
    gan_metrics['f1'].append(f1_score(y_val, y_pred_tuned, zero_division=0))
    gan_metrics['auc'].append(roc_auc_score(y_val, y_prob))
    gan_metrics['mcc'].append(matthews_corrcoef(y_val, y_pred_tuned))

    print(f"  Acc: {gan_metrics['accuracy'][-1]:.4f} | F1: {gan_metrics['f1'][-1]:.4f} | AUC: {gan_metrics['auc'][-1]:.4f}")

    if fold == 4:
        gan_model_final = model

print("\nGAN-Transformer CV Results:")
for m, v in gan_metrics.items():
    print(f"{m:12s}: {np.mean(v):.4f} ± {np.std(v):.4f}")

print("\n" + "="*60)
print("Training finished. Generating results and diagrams...")
print("="*60)

# ============================================================
# RESULTS + DIAGRAMS
# ============================================================

# 5-Fold detailed tables
tab_fold_results = pd.DataFrame({
    'Fold': [1,2,3,4,5],
    'Accuracy': tab_metrics['accuracy'],
    'Precision': tab_metrics['precision'],
    'Recall': tab_metrics['recall'],
    'F1-Score': tab_metrics['f1'],
    'ROC-AUC': tab_metrics['auc'],
    'MCC': tab_metrics['mcc']
})

gan_fold_results = pd.DataFrame({
    'Fold': [1,2,3,4,5],
    'Accuracy': gan_metrics['accuracy'],
    'Precision': gan_metrics['precision'],
    'Recall': gan_metrics['recall'],
    'F1-Score': gan_metrics['f1'],
    'ROC-AUC': gan_metrics['auc'],
    'MCC': gan_metrics['mcc']
})

print("\nTABTRANSFORMER - PER FOLD RESULTS")
print(tab_fold_results.round(4).to_string(index=False))

print("\nGAN-TRANSFORMER - PER FOLD RESULTS")
print(gan_fold_results.round(4).to_string(index=False))

# Final Test Predictions
test_preds_tab = tab_model_final.predict(X_test)
pred_col = [c for c in test_preds_tab.columns if 'prediction' in c.lower()][0]
y_test_pred_tab = test_preds_tab[pred_col].values.astype(int)
prob_cols = [c for c in test_preds_tab.columns if '1' in c and 'probability' in c.lower()]
y_test_prob_tab = test_preds_tab[prob_cols[0]].values if prob_cols else y_test_pred_tab

test_preds_gan = gan_model_final.predict(X_test)
pred_col = [c for c in test_preds_gan.columns if 'prediction' in c.lower()][0]
y_test_pred_gan = test_preds_gan[pred_col].values.astype(int)
prob_cols = [c for c in test_preds_gan.columns if '1' in c and 'probability' in c.lower()]
y_test_prob_gan = test_preds_gan[prob_cols[0]].values if prob_cols else y_test_pred_gan

# Final Test Table
test_table = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1-Score', 'ROC-AUC', 'MCC'],
    'TabTransformer': [
        round(accuracy_score(y_test, y_test_pred_tab), 4),
        round(precision_score(y_test, y_test_pred_tab, zero_division=0), 4),
        round(recall_score(y_test, y_test_pred_tab, zero_division=0), 4),
        round(f1_score(y_test, y_test_pred_tab, zero_division=0), 4),
        round(roc_auc_score(y_test, y_test_prob_tab), 4),
        round(matthews_corrcoef(y_test, y_test_pred_tab), 4)
    ],
    'GAN-Transformer': [
        round(accuracy_score(y_test, y_test_pred_gan), 4),
        round(precision_score(y_test, y_test_pred_gan, zero_division=0), 4),
        round(recall_score(y_test, y_test_pred_gan, zero_division=0), 4),
        round(f1_score(y_test, y_test_pred_gan, zero_division=0), 4),
        round(roc_auc_score(y_test, y_test_prob_gan), 4),
        round(matthews_corrcoef(y_test, y_test_pred_gan), 4)
    ]
})

print("\nFINAL TEST SET RESULTS")
print(test_table.to_string(index=False))

# Confusion Matrices
plt.figure(figsize=(6,5))
sns.heatmap(confusion_matrix(y_test, y_test_pred_tab), annot=True, fmt='d', cmap='Blues',
            xticklabels=['Low','High'], yticklabels=['Low','High'])
plt.title('TabTransformer - Confusion Matrix')
plt.savefig('cm_tab.png', dpi=300, bbox_inches='tight')
plt.show()

plt.figure(figsize=(6,5))
sns.heatmap(confusion_matrix(y_test, y_test_pred_gan), annot=True, fmt='d', cmap='Greens',
            xticklabels=['Low','High'], yticklabels=['Low','High'])
plt.title('GAN-Transformer - Confusion Matrix')
plt.savefig('cm_gan.png', dpi=300, bbox_inches='tight')
plt.show()

# Metrics Bar Chart
metrics = test_table['Metric']
x = np.arange(len(metrics))
width = 0.35
fig, ax = plt.subplots(figsize=(11,6))
ax.bar(x - width/2, test_table['TabTransformer'], width, label='TabTransformer', color='steelblue')
ax.bar(x + width/2, test_table['GAN-Transformer'], width, label='GAN-Transformer', color='#2ecc71')
ax.set_xticks(x)
ax.set_xticklabels(metrics)
ax.set_ylim(0, 1.15)
ax.legend()
ax.set_title('Metrics Comparison')
plt.tight_layout()
plt.savefig('metrics_comparison.png', dpi=300, bbox_inches='tight')
plt.show()

# ROC Curve
fpr_t, tpr_t, _ = roc_curve(y_test, y_test_prob_tab)
fpr_g, tpr_g, _ = roc_curve(y_test, y_test_prob_gan)
plt.figure(figsize=(8,6))
plt.plot(fpr_t, tpr_t, label=f'TabTransformer (AUC={auc(fpr_t,tpr_t):.3f})', color='steelblue')
plt.plot(fpr_g, tpr_g, label=f'GAN-Transformer (AUC={auc(fpr_g,tpr_g):.3f})', color='#2ecc71')
plt.plot([0,1],[0,1],'--', color='gray')
plt.legend()
plt.title('ROC Curve')
plt.savefig('roc_curve.png', dpi=300, bbox_inches='tight')
plt.show()

print("\nAll done! Files saved.")